title: "Agranelos Inventario API"
description: "GraphQL and REST API documentation for inventory management system"
baseurl: "/agranelos-functions-crud"
url: "https://diegobarrosa.github.io"

# Markdown processor
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Navigation
header_pages:
  - index.md
  - quick-reference.md

# Social links
github_username: DiegoBarrosA

# SEO settings
author: Diego Barros
twitter:
  username: DiegoBarrosA
  card: summary

# Build settings
theme: minima
remote_theme: jekyll/minima
incremental: true
safe: true

# Minima theme settings
minima:
  skin: auto
  social_links:
    github: DiegoBarrosA